#YAML Configuration
# path to file which has the rowwise multiline time series data
TS_PATH: './triplet/CRIME-_2015-01-01_2017-12-31.csv'
# path to file with name of the variables
NAME_PATH: './triplet/CRIME-_2015-01-01_2017-12-31.coords'
# path to log file for xgenesess inference
LOG_PATH: 'log.txt'
# xgenesses run parameters (these are not hyperparameters, Beg is 0, End is whatever tempral memory is)
END: 60
BEG: 0
# number of restarts (20 is good) ??
NUM: 2
# partition sequence?? - 0.5(we can specify different partition for each time series. XgenESeSS already has this capability)
PARTITION:
- 0.5
# number of models to use in prediction (using cynet binary)
model_nums:
- 85
# prediction horizons to test in unit of temporal quantization (using cynet binary)
horizons:
- 7
# length of run using cynet 365*4=1460(generally length of individual ts in split folder)
RUNLEN: 1460
#Periods to predict for
FLEX_TAIL_LEN: 365
# path to split series
DATA_PATH: './split_burg_10p/2015-01-01_2018-12-31'
# path to models
FILEPATH: './perturbed_payload2015_2017/models/'
# glob string that matches all the model.json files.
MODEL_GLOB: './perturbed_payload2015_2017/models/*model.json'
# number of processors to use for post process models
NUMPROC: 1
# path to where result files are stored
RESPATH: './perturbed_payload2015_2017/models/*model*res'
# path to XgenESeSS binary
XgenESeSS: './bin/XgenESeSS'
# do we run XgenESeSS binary locally, or do we produce a list of commands to be run via phnx ???  0,1
RUN_LOCAL: 1
# max distance cutoff in render network ???
MAX_DIST: 3
# min distance cutoff in render network??
MIN_DIST: 0.1
# max gamma cutoff in render network
MAX_GAMMA: 0.95
# min gamma cutoff in render network
MIN_GAMMA: 0.25
# colormap in render network
COLORMAP: 'Reds'
